Updating guide, adding location instructions
bespoken/bespoken-docs pull request #113
Opened 2020-02-20 16:32 UTC by ig-perez

Added instructions about how to change device location data for Alexa and Google.

2020-02-20 16:49 UTC, jkelvie commented
One question - what is the interplay between the main account address on Amazon and the device account? Is the account address used if one is not set on the device? Which takes precedence?

I would like to know, and our users probably would as well.

2020-02-20 16:50 UTC, dmarvp requested changes

2020-02-20 16:50 UTC, dmarvp commented on end-to-end/guide.md
> +| deviceLocation | An object to set a specific location value from where the requests are sent in Google Virtual Devices. It is composed by the `lat` and `lng` keys. Read [here](./faq#how-do-i-change
to follow the style of the other properties, put the link on `deviceLocation` instead of "Read here".

2020-02-20 16:50 UTC, dmarvp commented on end-to-end/faq.md
> +## **How do I change my Virtual Device location to test location-specific features?**
How do I change my default Virtual Device location to test location-specific features?

2020-02-20 16:50 UTC, dmarvp commented on end-to-end/faq.md
> +Our Virtual Devices are created without a specific location. If you want to set it, follow the instructions below:
> Our Virtual Devices are created without a specific location.

That's not entirely true. Even if we don't set one by default, both Alexa and Google will infer a location from your IP, account region, etc. To make it simpler, I would just remove this line and go directly to the instructions.

2020-02-20 16:55 UTC, dmarvp commented
@ig-perez , we could answer @jkelvie's question in another faq right before this one. `What is the default location for a virtual device?` and then proceed to explain for Alexa and Google. You can find the precedence for Google here:

![image](https://user-images.githubusercontent.com/6411740/74958914-b0f2d600-53d7-11ea-8d73-fb1323f38a1d.png)

For Amazon, we need to test with accounts from other regions and then changing a device location.

2020-02-20 18:39 UTC, ig-perez commented on end-to-end/guide.md
> +| deviceLocation | An object to set a specific location value from where the requests are sent in Google Virtual Devices. It is composed by the `lat` and `lng` keys. Read [here](./faq#how-do-i-change
ok

2020-02-20 18:40 UTC, ig-perez commented on end-to-end/faq.md
> +Our Virtual Devices are created without a specific location. If you want to set it, follow the instructions below:
Yeah, better

2020-02-20 18:41 UTC, ig-perez commented
> 
> 
> @ig-perez , we could answer @jkelvie's question in another faq right before this one. `What is the default location for a virtual device?` and then proceed to explain for Alexa and Google. You can find the precedence for Google here:
> 
> ![image](https://user-images.githubusercontent.com/6411740/74958914-b0f2d600-53d7-11ea-8d73-fb1323f38a1d.png)
> 
> For Amazon, we need to test with accounts from other regions and then changing a device location.

Good idea, I'll add the information on another question, but I partially explained for Amazon in current FAQ question.

2020-02-20 18:42 UTC, ig-perez commented on end-to-end/faq.md
> +## **How do I change my Virtual Device location to test location-specific features?**
Guess better not to use default here.

2020-02-20 18:47 UTC, ig-perez commented
> 
> 
> One question - what is the interplay between the main account address on Amazon and the device account? Is the account address used if one is not set on the device? Which takes precedence?
> 
> I would like to know, and our users probably would as well.

@jkelvie yes, it takes the address from your main Amazon account as I wrote in the instructions, but I'll give more details on a separate question based on Diego's suggestion

2020-02-20 21:56 UTC, ig-perez commented
@dmarvp @jkelvie , I have added an extra question about the default location for virtual devices. Oddly, I can't reproduce the behavior I saw yesterday with my account (I deleted my current address and a virtual device took previous address for location). For US accounts, Atlanta and San José are used when creating virtual devices, no matter if the Amazon account has an address or not. This behavior was not seen for the UK.

2020-02-20 22:55 UTC, jkelvie commented
One clarification - when outside the US, if no address is set on the device, does it the use the account address as a fallback?

2020-02-20 23:09 UTC, ig-perez commented
@jkelvie no, in the UK the device address was always empty, and when asking for the weather alexa responded "add an address"-like message

2020-02-21 00:12 UTC, jkelvie commented
Okay, please make note of that behavior in the FAQ. I think it is helpful to have it memorialized since it comes up as a question somewhat frequently.

2020-02-21 15:57 UTC, ig-perez commented
@jkelvie I added more information as requested, please let us know if it is clear now.

2020-02-21 17:33 UTC, jkelvie approved these changes

2020-02-21 22:19 UTC, dmarvp approved these changes

2020-02-21 22:19 UTC, merged