removes async and batchEnabled references
bespoken/bespoken-docs pull request #171
Opened 2022-12-21 00:02 UTC by dmarvp

This is for: https://app.clickup.com/t/3bp9dhh
and after completing: https://app.clickup.com/t/3bp9dh6

Changes:
- Removed any reference to `asyncMode`
- Removed any reference to `batchEnabled`
  - This included the "Goto and exit" section. 
- Updated the node minimal requirements
- Reordered the configuration section to move the Jest options **after** our regular `testing.json` options
- Added some missing options
- Removed the "bst test options" section to avoid confusion.
- Removed everything related to SMAPI
- Removed cardContent / cardTitle examples and mentions 
- Moved the available voices to their own section
- Some configuration options were removed only for simplification (ie: asyncE2EWaitInterval)

Things we might need to revisit:
- Goto and exit for the current implementation (is there a demand for it?)
- SMAPI
- Removed configuration parameters: should they have their own/internal place? should we clean the code associated with the ones we'll no longer use?
  - html
  - skillId
  - stage
  - type = simulation
  - batchEnabled
  - asyncMode
  - asyncE2EWaitInterval
  - virtualDeviceBaseURL

2022-12-22 16:14 UTC, jkelvie requested changes

2022-12-22 16:14 UTC, jkelvie commented on end-to-end/guide.md
> +* [Node.js v12 or superior](https://nodejs.org/en/download/)
"or above"

2022-12-22 16:14 UTC, jkelvie commented on end-to-end/guide.md
> +The following are the different configuration options available ordered alphabetically:
The following are the different configuration options available:

2022-12-22 16:14 UTC, jkelvie commented on end-to-end/guide.md
> +Additionally, you can override [Jest options](https://facebook.github.io/jest/docs/en/configuration.html) under the "jest" key. Here are our default ones:
"Here are the default settings:"

2022-12-22 16:14 UTC, jkelvie commented on end-to-end/guide.md
> +Speaking of environment variables, you can use them inside the `testing.json` file by using the `${variable}` format.
"Regarding environment variables, you can reference them inside the `testing.json` file with the `${ENVIRONMENT_VARIABLE}` format"

2022-12-22 16:14 UTC, jkelvie commented on end-to-end/guide.md
> +| maxAsyncE2EResponseWaitTime | Set an interval in milliseconds to wait before stop looking for new results and throwing an error - defaults to 15000 |
Can we alias this as "maxWaitTimeForResponse". I think this name is confusing and overly complicated (as well as reference async again)

2022-12-27 22:13 UTC, dmarvp commented on end-to-end/guide.md
> +| maxAsyncE2EResponseWaitTime | Set an interval in milliseconds to wait before stop looking for new results and throwing an error - defaults to 15000 |
I made the change in advance but 'll create a ticket for this.

2022-12-28 18:15 UTC, jkelvie approved these changes

2023-01-26 18:47 UTC, merged