Adding questions to support the account linking process
bespoken/bespoken-docs pull request #78
Opened 2019-10-04 21:37 UTC by ig-perez

Please check the two questions I added in order to clear the account linking process up.

2019-10-04 22:30 UTC, dmarvp requested changes

2019-10-04 22:30 UTC, dmarvp commented on end-to-end/faq.md
> +The account linking process is part of your app's functionality. The features provided by the external backend might be part of your functional scope or extend it. Either way, the Bespoken Tools setu
I would leave this line simply as 

> The Bespoken Tools setup is agnostic to the account linking process. If you want to test a voice app that requires account linking you should first link your voice app to the Amazon or Google account you'll use to run your tests and then proceed testing as usual.

2019-10-04 22:30 UTC, dmarvp commented on end-to-end/faq.md
> +As the account linking process involves __visual__ user interaction between your voice service provider and an external backend, you need to use an external web automation tool like Selenium to accom
and this one as:
> As the account linking process involves __visual__ user interaction between a voice platform and your backend, you need to use an external web automation tool like Selenium to accomplish it. This visual interaction test script can be later linked to the audio interaction test scripts created with Bespoken Tools. Please [contact us](mailto:sales@bespoken.io) in case you want to discuss further as we can assist you in creating the visual test scripts with Selenium.

2019-10-08 19:45 UTC, jkelvie commented on end-to-end/faq.md
> +The account linking process is part of your app's functionality. The features provided by the external backend might be part of your functional scope or extend it. Either way, the Bespoken Tools setu
The question should just be:
"How do I test a voice app that requires account linking?"

The answer should be:

To test a voice app that requires account linking, simply link the account as you normally would within the Alexa and/or Google management screens. Once the account linking process is completed, you can talk to the skill and access account-specific information via your virtual device. It's that easy!

Of course, make sure the Alexa/Google account you are using is the same one that your virtual device is associated with.  

If you are unsure what Amazon account your virtual device is associated with, try sending this to Alexa:
`bst speak --token <TOKEN> what is my name`

2019-10-08 19:50 UTC, jkelvie commented on end-to-end/faq.md
> +As the account linking process involves __visual__ user interaction between your voice service provider and an external backend, you need to use an external web automation tool like Selenium to accom
The question should be "Can I test the account linking process itself with Bespoken?"

I like Diego's answer. I would also add this in a second paragraph:
"Of course, if you are just trying to test specific account scenarios (and not the account linking process itself), we recommend setting up virtual devices linked to specific accounts. You only need to do this once, and then you can test these scenarios as needed essentially forever. Read more at this [FAQ entry](/end-to-end/faq/#How-do-I-test-a-voice-app-that-requires-account-linking).

2019-10-15 17:42 UTC, ig-perez commented
Please review latest version

2019-10-15 20:11 UTC, jkelvie commented on end-to-end/faq.md
> +## <a id="anchorToAccLinking!stQ"></a>**How do I test a voice app that requires account linking?**
Is the explicit anchor needed? Markdown automaticlly generates anchors:
https://deploy-preview-78--zen-pike-2b04c4.netlify.com/end-to-end/faq/#how-do-i-test-a-voice-app-that-requires-account-linking

2019-10-15 20:12 UTC, jkelvie reviewed
I added one comment

2019-10-16 19:37 UTC, jkelvie approved these changes

2019-10-16 19:38 UTC, merged