Update documentation
bespoken/bespoken-docs pull request #9
Opened 2018-10-03 17:00 UTC by jperata

Relates to https://github.com/bespoken/bst/issues/505

2018-10-04 15:49 UTC, jperata commented
@ecruzado at the moment this is for the include/exclude tags and the override options with an example.
Add a ticket for the other ones not documented and we will assign the time to update them.

2018-10-04 16:32 UTC, jkelvie requested changes

2018-10-04 16:32 UTC, jkelvie commented on end-to-end/guide.md
> +* [include and exclude](#including-or-excluding-tests-using-tags) - Runs or Skip the tests having the particular indicated tags
Please put this in alphabetical order (as the other ones are)

2018-10-04 16:32 UTC, jkelvie commented on end-to-end/guide.md
> +By specifying tags in particular tests you can then run only the tests you want. Let's say you have tests specific to the first time a user use your skill, we are going to apply the tag "FirstUse" to
"first time a user **uses** your skill"

2018-10-04 16:32 UTC, jkelvie commented on end-to-end/guide.md
> +- tags: FirstUse
Can you show two tags just to clarify how they are specified? "FirstUse, Alexa"

2018-10-04 16:32 UTC, jkelvie commented on end-to-end/guide.md
> +If you want to run all the tests that have that particular tag, you can edit testing.json to indicate that those are the ones to run by adding the "include" property:
"Note that multiple tags can be applied to a test, as a comma-delimited list."

2018-10-04 16:32 UTC, jkelvie commented on end-to-end/guide.md
> +Remember you can also use the override properties when executing the bst test command and also combine include and exclude together. This command will run all the tests that have either FirstUse or R
Awesome functionality (and good docs too) :-)

2018-10-04 22:10 UTC, jperata commented on end-to-end/guide.md
> +If you want to run all the tests that have that particular tag, you can edit testing.json to indicate that those are the ones to run by adding the "include" property:
included after the example

2018-10-05 12:52 UTC, jkelvie requested changes

2018-10-05 12:52 UTC, jkelvie commented on end-to-end/guide.md
> +* [include and exclude](#including-or-excluding-tests-using-tags) - Runs or Skip the tests having the particular indicated tags
"having the **specified** tags"

2018-10-05 12:52 UTC, jkelvie commented on end-to-end/guide.md
> +- tags: FirstUse,Alexa
Add a space after the comma

2018-10-05 21:02 UTC, jkelvie approved these changes

2018-10-05 21:43 UTC, merged